### ISSUE TITLE
Déplacer dans une nouvelle classe « DerbyUtils » tout le code d'initialisation de la base de données

### ISSUE THREAD

**Issue by fromltow0** [Riboshom/log240-h2015-08#2]
* Cette classe doit être implémentée sous forme de Singleton.
* Le constructeur de ce Singleton devrait charger le pilote (« driver ») Derby, créer et stocker la connexion à la BD dans un attribut privé, et créer les tables (au besoin). 
* Une fois cette tâche réalisée, il ne devrait rester aucun code d'accès à la BD dans Financej.java. L'obtention de la connexion dans cette classe devrait se faire via un appel à DerbyUtils.getConnection();

**Comment by Simix48** [comment]
Done
